### ISSUE TITLE
Card Carousel Tab order wonky

### ISSUE THREAD

**Issue by EbizSean** [aut0poietic/ali#34]
http://aut0poietic.github.io/ali/card-carousel.html

When tabbing through the carousel cards, I can get to a point where tabbing from the [Next] button will skip cards (usually to one card in the middle and then to the final card). For example, from the [Next] button on card #2, it'll skip to card #5, and then card #10. 

This behavior is true in Chrome and IE.

**Comment by aut0poietic** [comment]
Oversight on my part. Need to modify styles on non-visible cards to actually be non-visible ( not just invisible to AT )

**Comment by aut0poietic** [comment]
Turns out this is a larger problem with the behavior of the carousel and cards and focus.

I have two options for fixing things: 

- [ ]  Move focus to the next valid button element.
- [ ]  Move focus to the card itself

I'm going to spend some time experimenting with both methods. My guess is that focusing the card itself is going to be a superior solution because focusing the card **may** read the entire active side of the card while setting focus the button will cause only the button to be read, but be in slightly better context.

**Comment by aut0poietic** [comment]
Like focusing the card much better. the button itself didn't provide enough context and could possibly rob the AT of announcing content changes.
