### ISSUE TITLE
NVDA reading dual-answer loop

### ISSUE THREAD

**Issue by EbizSean** [aut0poietic/ali#38]
http://aut0poietic.github.io/ali/answer-set.html

When I select the drop-down menu via keyboard, NVDA is reading "Question Text / Last Selected / Submit button / Current Selected" as one long entry or loop.

**Comment by aut0poietic** [comment]
Because aria-live/aria-atomic are set initially to assertive/true NVDA is interpreting the change in the SELECT as an event requiring announcing.

I've rebuilt the component to start with aria-live="off" aria-atomic="true" and` just before updating the flag ( an addition ) aria-live is set to "assertive" hopefully this will cause the entire form to be re-read.
